name: py-and-r
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - r-base
  - r-tidyverse
  - r-irkernel
  - pip
  - pip:
      - rpy2
